version: '3.8'

services: 
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/srv/data
      - ./data/.nomic:/root/.nomic/
      - ./models:/srv/models
      - ./configs:/srv/configs
      - ./personalities:/srv/personalities
    ports: 
      - "9600:9600"
